source/index.md
Good to be merged after review.
cc @kylef
=> HP content kick off

source/index.md
The page changed and this link was never updated.
=> Update link from homepage to the tutorial

source/javascripts/all.js, source/layouts/layout.erb, source/stylesheets/all.css
Fixing visual issues, mobile bug and footer design.
=> Fixed issues #15, #16, #11

source/index.md
=> Consistently use `+` instead of `-` for line items

source/layouts/layout.erb
=> Append "| API Blueprint" to html title

Gemfile, Gemfile.lock, config.rb
This pull request adds "live-reload" to the development server. Which means you can change source / js / styles and it will make the web browser reload the page automatically. This should speed up development.
/cc @tjerabek
=> Enable live reload for development

source/layouts/layout.erb, source/stylesheets/all.css
=> Add twitter and GitHub star buttons

source/layouts/layout.erb
=> Add Google Analytics

source/tools.html.erb
This is an effort to make the search field more prominent
=> Make search focussed on page load on tools section

source/tools.html.erb
=> Add a link to add your own tool

source/developers.md
Use API Elements instead of Refract API Description namespace
=> API Elements

data/tools.yaml
Apish consumes APIB or Swagger and creates a mock server - https://github.com/JackuB/apish
=> Added apish to tools

source/stylesheets/all.css
@tjerabek told me that we can merge this.
=> Responsive fix

Gemfile, Gemfile.lock, config.rb
Tested locally and now works perfectly
=> Fixing the deploy pipeline

source/stylesheets/all.css
=> Visually differentiate between sub list items

source/developers.md
See https://github.com/apiaryio/drafter/pull/341
=> Update development instructions for Drafter 3

data/tools.yaml
During the last weeks/months/free time I've been working on an extension for VSCode to enable a better API Blueprint integration.
=> Add vscode-apielements

data/tools.yaml
Utility to create MSON on the base JSON
=> Add MSON generator

data/tools.yaml
Added SwiftAPI which convert an API Blueprint into executable Swift code.
=> Added SwiftAPI

data/tools.yaml
- Utility to generate API Blueprint from python docstring.
=> add python pyabp tool

data/tools.yaml
I have been working/using this gem for a while in my projects. I think it would be useful !
=> Add blueprint-agreement gem

data/tools.yaml
[node.js] test2doc.js helps you generate API documentation from your tests/specs.
=> Add test2doc.js tool

data/tools.yaml
I was asked to add my little tool to the list. Here it is :)
=> Add pmtoapib to the tools list

data/tools.yaml
Hello! I would like to share a gem for validation documentation in tests
=> Add gem fitting for testing

data/tools.yaml
Tool to create SDK client in PHP from API blueprint apib file.
=> Add Blueprint SDK Maker to tools

data/tools.yaml
Hi guys,
we created a tool for generating API Blueprint for Phoenix Framework with aglio.
I hope you will find it useful. :)
=> Add BlueBird to tools

data/tools.yaml
Hello! I would like to share a gem for validate requests and responses against API Blueprint specifications
=> Add gem esplanade for validation

data/tools.yaml
=> Remove dead link to Apib::MockServer

data/tools.yaml
Playground URL: https://blueprint-dash.surge.sh/
=> New playground for new people to experiment on 😀

data/tools.yaml
Parse Postman collection to blueprint documentation
=> I created new parser

.circleci/config.yml, Gemfile, Gemfile.lock, config.rb
Solution from https://forum.middlemanapp.com/t/definitive-guide-to-middleman-4-and-bootstrap/2454/14
=> fix bootstrap 4.3.1 upgrade

data/tools.yaml
I have recently created a tool called API Documenter, which uses MSON (API Blueprint) to generate API documents. So, I thought to add that editor to the list of available API Blueprint editor list on here.
Thank you so much.
=> Added apidocumenter.com as a new editor.
