circle.yml

This pull request ensures that the version of bundler used in CI is the same as the version used to develop apiblueprint.org by utilising the version in the lock file.
```
BUNDLED WITH
1.11.2
```
Without this change, Circle CI was using an older version, and subsequently causing the website to no longer automatically deploy. This is because the `Gemfile.lock` file was being updated with a different version. The deploy process will not let you deploy  when you have local changes thus failing.
```
Changes not staged for commit:
modified:   ../Gemfile.lock
```

Use the locked version of bundler in Circle CI

---

data/tools.yaml
source/tools.html.erb

* Add sections to the tooling page for:
* **Mock servers** - creates a local web server from blueprint requests and responses
* **Renderers** - hosts blueprints as HTML or other formats
* **Converters** - converts blueprints to/from some other format (generally HTML) 
* Apply sections to existing tools in `tools.yaml`
1. Section naming. Do these names seem clear and make sense?
2. Should more tags apply to the Apiary tool listing? For example, it overlaps with Dredd but also includes testing/mock servers, rendering, et cetera

Add additional tooling sections

---

Gemfile
Gemfile.lock
circle.yml

- Updates to Ruby 2.3.1
- Updates to Rouge release instead of installing from Git. The API Blueprint lexer was released in Rouge.

Update Ruby and Rouge

---

Rakefile
circle.yml
data/tools.yaml

As reported in #59, there is a YAML syntax error in our tools list. This pull request fixes that error and adds parsing the file during CI so that we will catch errors in PRs in the future.
The following error will be emitted when the tools.yml has a syntax error:
```shell
$ rake validate-tools
rake aborted!
Psych::SyntaxError: (data/tools.yaml): could not find expected ':' while scanning a simple key at line 268 column 3
```

Fix a YAML error in the tools section and lint the tools on CI

---

data/tools.yaml

Snowboard is my (another ^^) attempt to provides pleasant experience when working with API blueprint.
Snowboard goal is provides single binary application, so anyone can just download it and start producing documentation, while allows developer to create and use custom documentation template.
https://github.com/subosito/snowboard is next version of [Iglo](https://github.com/subosito/iglo). Both written using Golang. The main difference is Iglo use drafter command line and AST, while snowboard  using drafter library via cgo and Refract.

Added snowboard to tools section

---

source/tools.html.erb

This PR allows a user to copy the link directly to a tool filter. This makes it easier for people to directly link to a subset of the tools such as pointing someone else to the tools of API Blueprint. The https://apiblueprint.org/tools.html#editor link could be used.
Closes #23

Support permalinks to tool filters

---

data/tools.yaml

docprint generates Clean Static HTML documentation from API Blueprint file. Provides waypoints, attributes and multiple language code snippets.

Added docprint

---

data/tools.yaml

We shouldn't promote matter_compiler as it is deprecated and not supported.

Remove matter_compiler as it is deprecated

---

data/tools.yaml

Draughtsman  is an API Blueprint Parser for Python 3. Draughtsman is a Python binding for the API Blueprint parser drafter.

Add Draughtsman to tools

---

data/tools.yaml

Dox is a Ruby gem, it generates API documentation from RSpec controller/request specs in a Rails application. It formats the tests output in the API Blueprint format.
https://github.com/infinum/dox

Add Dox to tools

---

data/tools.yaml

On the page there were second tools
https://apiblueprint.org/tools.html#tools

remove duplicate tools

---

data/tools.yaml

django-apiblueprint-view is a django app for rendering docs written in API Blueprint to HTML

Add django-apiblueprint-view to tools

---

data/tools.yaml

Vanadia is my utility hosted in https://github.com/bukalapak/vanadia, which take an API Blueprint `.apib` file and convert it into a Postman collection in 2.1 format. It is a part of my internship project in Bukalapak, but I've committed myself to maintain it to join the open source community.
Vanadia uses [Snowboard](https://github.com/bukalapak/snowboard), an API Blueprint parser and renderer; thus, Vanadia is also using the latest stable Drafter under-the-hood, which differs it from other converter. Like Snowboard, Vanadia is written in Go.

Add Vanadia into API Blueprint tools

---

data/tools.yaml

- Adds a tool for generating Blueprint API markup or the Apiary API from a Postman collection.
git clone https://github.com/p8ul/postman2apiary.git
cd app
CLI application Application takes three arguments.
USAGE: $ python run.py [postman.json-file] [output-file.apid]
postman.json-file: JSON file exported from Postman collection
output-file.apid: Name of your API markup file to be generated.

Convert postman collection to api-blueprint markup

---

source/developers.html.md

Drafter has been added to Homebrew core and we can now install it directly.
```shell
$ brew install drafter
```

Fix drafter installation on homebrew

---

data/tools.yaml

Snowboard seems to have been rewritten in JavaScript, remove reference to Golang.

Update snowboard description in tools

---

source/developers.html.md

This updates the installation instructions on the website for CMake, instead of repeating the detailed instructions I've linked to them (https://github.com/apiaryio/drafter/pull/723). I've removed mentions of specific platform (Linux), the instructions work on Windows too (and possible BSD's although that is not tested).

Update installation instructions for CMake

---

source/developers.html.md

Updated C code example in developers section to match breaking C API changes introduced in https://github.com/apiaryio/drafter/pull/766 .

(chore) drafter c api code example to match drafter@v5.0.0-rc.1

---

source/documentation/mson/cheatsheet.html.md.erb

This brings a new page to apiblueprint.org containing an example orientated document showing some MSON features in the context of API Blueprint. It is not intended to be a complete documentation (there's a prior specification and tutorial), but to showcase some common caveats (escaping) and show common syntax in the comntext of API Blueprint.

Add a cheatsheet for MSON

---

data/tools.yaml

Blueprint Dash now became BlueprintStack (https://blueprintstack.io) with more features for new people to experiment with the API blueprint spec.

Updating tools section
